### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by bajtos** [davidmarkclements/events.once#2]
It's great to see the new `events.once` API available for older Node.js versions too, thank you for that ❤️ 

Have you considered adding a `.d.ts` file describing the `once` function, to make this module easier to use from TypeScript?

**Comment by 0x326** [comment]
I created a draft at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39023

**Comment by davidmarkclements** [comment]
I’m also happy to accept a PR for a d.ts file on the proviso that it’s maintained by members of typescript community

**Comment by 0x326** [comment]
@davidmarkclements If you want the `.d.ts` to maintained completely by the TypeScript community, then the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) project is probably your best bet.  

My PR has been merged, so users can now use this library with TypeScript by running:

```bash
npm install --save events.once
npm install --save-dev @types/events.once
```
